package com.dongfangyuxin.common.dao.bean;

import java.util.Date;

public class AttendanceInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.STAFF_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String staffCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.START_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.END_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..attendance_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.ID
     *
     * @return the value of sagittarius..attendance_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.ID
     *
     * @param id the value for sagittarius..attendance_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.STAFF_CODE
     *
     * @return the value of sagittarius..attendance_info.STAFF_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.STAFF_CODE
     *
     * @param staffCode the value for sagittarius..attendance_info.STAFF_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode == null ? null : staffCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.START_TIME
     *
     * @return the value of sagittarius..attendance_info.START_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.START_TIME
     *
     * @param startTime the value for sagittarius..attendance_info.START_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.END_TIME
     *
     * @return the value of sagittarius..attendance_info.END_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.END_TIME
     *
     * @param endTime the value for sagittarius..attendance_info.END_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.S_CREATOR
     *
     * @return the value of sagittarius..attendance_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.S_CREATOR
     *
     * @param sCreator the value for sagittarius..attendance_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.S_CREATE_DATE
     *
     * @return the value of sagittarius..attendance_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.S_CREATE_DATE
     *
     * @param sCreateDate the value for sagittarius..attendance_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.S_OPERATOR
     *
     * @return the value of sagittarius..attendance_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.S_OPERATOR
     *
     * @param sOperator the value for sagittarius..attendance_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..attendance_info.S_OPERATOR_DATE
     *
     * @return the value of sagittarius..attendance_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..attendance_info.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for sagittarius..attendance_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}