package com.dongfangyuxin.common.dao.bean;

import java.util.Date;

public class CarInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.TYPE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.STATUS
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.MEMO
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..car_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.ID
     *
     * @return the value of sagittarius..car_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.ID
     *
     * @param id the value for sagittarius..car_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.CODE
     *
     * @return the value of sagittarius..car_info.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.CODE
     *
     * @param code the value for sagittarius..car_info.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.TYPE
     *
     * @return the value of sagittarius..car_info.TYPE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.TYPE
     *
     * @param type the value for sagittarius..car_info.TYPE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.STATUS
     *
     * @return the value of sagittarius..car_info.STATUS
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.STATUS
     *
     * @param status the value for sagittarius..car_info.STATUS
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.MEMO
     *
     * @return the value of sagittarius..car_info.MEMO
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.MEMO
     *
     * @param memo the value for sagittarius..car_info.MEMO
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.S_CREATOR
     *
     * @return the value of sagittarius..car_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.S_CREATOR
     *
     * @param sCreator the value for sagittarius..car_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.S_CREATE_DATE
     *
     * @return the value of sagittarius..car_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.S_CREATE_DATE
     *
     * @param sCreateDate the value for sagittarius..car_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.S_OPERATOR
     *
     * @return the value of sagittarius..car_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.S_OPERATOR
     *
     * @param sOperator the value for sagittarius..car_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..car_info.S_OPERATOR_DATE
     *
     * @return the value of sagittarius..car_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..car_info.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for sagittarius..car_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}