package com.dongfangyuxin.common.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class ExpenseInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.AMOUNT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.TIME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.TASK_CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String taskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expense_info.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.ID
     *
     * @return the value of expense_info.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.ID
     *
     * @param id the value for expense_info.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.CODE
     *
     * @return the value of expense_info.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.CODE
     *
     * @param code the value for expense_info.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.AMOUNT
     *
     * @return the value of expense_info.AMOUNT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.AMOUNT
     *
     * @param amount the value for expense_info.AMOUNT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.TIME
     *
     * @return the value of expense_info.TIME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.TIME
     *
     * @param time the value for expense_info.TIME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.OPERATOR
     *
     * @return the value of expense_info.OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.OPERATOR
     *
     * @param operator the value for expense_info.OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.TASK_CODE
     *
     * @return the value of expense_info.TASK_CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.TASK_CODE
     *
     * @param taskCode the value for expense_info.TASK_CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.S_CREATOR
     *
     * @return the value of expense_info.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.S_CREATOR
     *
     * @param sCreator the value for expense_info.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.S_CREATE_DATE
     *
     * @return the value of expense_info.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.S_CREATE_DATE
     *
     * @param sCreateDate the value for expense_info.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.S_OPERATOR
     *
     * @return the value of expense_info.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.S_OPERATOR
     *
     * @param sOperator the value for expense_info.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expense_info.S_OPERATOR_DATE
     *
     * @return the value of expense_info.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expense_info.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for expense_info.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}