package com.dongfangyuxin.common.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class InventoryInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.MATERIAL_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String materialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..inventory_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.ID
     *
     * @return the value of sagittarius..inventory_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.ID
     *
     * @param id the value for sagittarius..inventory_info.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.MATERIAL_CODE
     *
     * @return the value of sagittarius..inventory_info.MATERIAL_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.MATERIAL_CODE
     *
     * @param materialCode the value for sagittarius..inventory_info.MATERIAL_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.QUANTITY
     *
     * @return the value of sagittarius..inventory_info.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.QUANTITY
     *
     * @param quantity the value for sagittarius..inventory_info.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.AMOUNT
     *
     * @return the value of sagittarius..inventory_info.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.AMOUNT
     *
     * @param amount the value for sagittarius..inventory_info.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.S_CREATOR
     *
     * @return the value of sagittarius..inventory_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.S_CREATOR
     *
     * @param sCreator the value for sagittarius..inventory_info.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.S_CREATE_DATE
     *
     * @return the value of sagittarius..inventory_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.S_CREATE_DATE
     *
     * @param sCreateDate the value for sagittarius..inventory_info.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.S_OPERATOR
     *
     * @return the value of sagittarius..inventory_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.S_OPERATOR
     *
     * @param sOperator the value for sagittarius..inventory_info.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..inventory_info.S_OPERATOR_DATE
     *
     * @return the value of sagittarius..inventory_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..inventory_info.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for sagittarius..inventory_info.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}