package com.dongfangyuxin.common.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MaterialBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.NAME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.UNIT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.PRICE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.IMAGE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.ID
     *
     * @return the value of material.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.ID
     *
     * @param id the value for material.ID
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.CODE
     *
     * @return the value of material.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.CODE
     *
     * @param code the value for material.CODE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.NAME
     *
     * @return the value of material.NAME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.NAME
     *
     * @param name the value for material.NAME
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.UNIT
     *
     * @return the value of material.UNIT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.UNIT
     *
     * @param unit the value for material.UNIT
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.PRICE
     *
     * @return the value of material.PRICE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.PRICE
     *
     * @param price the value for material.PRICE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.IMAGE
     *
     * @return the value of material.IMAGE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.IMAGE
     *
     * @param image the value for material.IMAGE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.S_CREATOR
     *
     * @return the value of material.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.S_CREATOR
     *
     * @param sCreator the value for material.S_CREATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.S_CREATE_DATE
     *
     * @return the value of material.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.S_CREATE_DATE
     *
     * @param sCreateDate the value for material.S_CREATE_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.S_OPERATOR
     *
     * @return the value of material.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.S_OPERATOR
     *
     * @param sOperator the value for material.S_OPERATOR
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.S_OPERATOR_DATE
     *
     * @return the value of material.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for material.S_OPERATOR_DATE
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}