package com.dongfangyuxin.common.dao.bean;

import java.util.Date;

public class MaterialReturningSlipBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String taskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.COUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.OPERATING_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date operatingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.ORDER_PERSON
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String orderPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.ORDER_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_slip.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.ID
     *
     * @return the value of sagittarius..material_returning_slip.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.ID
     *
     * @param id the value for sagittarius..material_returning_slip.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.CODE
     *
     * @return the value of sagittarius..material_returning_slip.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.CODE
     *
     * @param code the value for sagittarius..material_returning_slip.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.TASK_CODE
     *
     * @return the value of sagittarius..material_returning_slip.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.TASK_CODE
     *
     * @param taskCode the value for sagittarius..material_returning_slip.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.COUNT
     *
     * @return the value of sagittarius..material_returning_slip.COUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.COUNT
     *
     * @param count the value for sagittarius..material_returning_slip.COUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.OPERATOR
     *
     * @return the value of sagittarius..material_returning_slip.OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.OPERATOR
     *
     * @param operator the value for sagittarius..material_returning_slip.OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.OPERATING_TIME
     *
     * @return the value of sagittarius..material_returning_slip.OPERATING_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getOperatingTime() {
        return operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.OPERATING_TIME
     *
     * @param operatingTime the value for sagittarius..material_returning_slip.OPERATING_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setOperatingTime(Date operatingTime) {
        this.operatingTime = operatingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.ORDER_PERSON
     *
     * @return the value of sagittarius..material_returning_slip.ORDER_PERSON
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getOrderPerson() {
        return orderPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.ORDER_PERSON
     *
     * @param orderPerson the value for sagittarius..material_returning_slip.ORDER_PERSON
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setOrderPerson(String orderPerson) {
        this.orderPerson = orderPerson == null ? null : orderPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.ORDER_TIME
     *
     * @return the value of sagittarius..material_returning_slip.ORDER_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.ORDER_TIME
     *
     * @param orderTime the value for sagittarius..material_returning_slip.ORDER_TIME
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.S_CREATOR
     *
     * @return the value of sagittarius..material_returning_slip.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.S_CREATOR
     *
     * @param sCreator the value for sagittarius..material_returning_slip.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.S_CREATE_DATE
     *
     * @return the value of sagittarius..material_returning_slip.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.S_CREATE_DATE
     *
     * @param sCreateDate the value for sagittarius..material_returning_slip.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.S_OPERATOR
     *
     * @return the value of sagittarius..material_returning_slip.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.S_OPERATOR
     *
     * @param sOperator the value for sagittarius..material_returning_slip.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_slip.S_OPERATOR_DATE
     *
     * @return the value of sagittarius..material_returning_slip.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_slip.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for sagittarius..material_returning_slip.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}