package com.dongfangyuxin.common.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MaterialReturningDetailBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String taskCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private String sOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sagittarius..material_returning_detail.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    private Date sOperatorDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.ID
     *
     * @return the value of sagittarius..material_returning_detail.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.ID
     *
     * @param id the value for sagittarius..material_returning_detail.ID
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.CODE
     *
     * @return the value of sagittarius..material_returning_detail.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.CODE
     *
     * @param code the value for sagittarius..material_returning_detail.CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.TASK_CODE
     *
     * @return the value of sagittarius..material_returning_detail.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.TASK_CODE
     *
     * @param taskCode the value for sagittarius..material_returning_detail.TASK_CODE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.QUANTITY
     *
     * @return the value of sagittarius..material_returning_detail.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.QUANTITY
     *
     * @param quantity the value for sagittarius..material_returning_detail.QUANTITY
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.AMOUNT
     *
     * @return the value of sagittarius..material_returning_detail.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.AMOUNT
     *
     * @param amount the value for sagittarius..material_returning_detail.AMOUNT
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.S_CREATOR
     *
     * @return the value of sagittarius..material_returning_detail.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsCreator() {
        return sCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.S_CREATOR
     *
     * @param sCreator the value for sagittarius..material_returning_detail.S_CREATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreator(String sCreator) {
        this.sCreator = sCreator == null ? null : sCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.S_CREATE_DATE
     *
     * @return the value of sagittarius..material_returning_detail.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsCreateDate() {
        return sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.S_CREATE_DATE
     *
     * @param sCreateDate the value for sagittarius..material_returning_detail.S_CREATE_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsCreateDate(Date sCreateDate) {
        this.sCreateDate = sCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.S_OPERATOR
     *
     * @return the value of sagittarius..material_returning_detail.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public String getsOperator() {
        return sOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.S_OPERATOR
     *
     * @param sOperator the value for sagittarius..material_returning_detail.S_OPERATOR
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperator(String sOperator) {
        this.sOperator = sOperator == null ? null : sOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sagittarius..material_returning_detail.S_OPERATOR_DATE
     *
     * @return the value of sagittarius..material_returning_detail.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public Date getsOperatorDate() {
        return sOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sagittarius..material_returning_detail.S_OPERATOR_DATE
     *
     * @param sOperatorDate the value for sagittarius..material_returning_detail.S_OPERATOR_DATE
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    public void setsOperatorDate(Date sOperatorDate) {
        this.sOperatorDate = sOperatorDate;
    }
}