package com.dongfangyuxin.common.dao;

import com.dongfangyuxin.common.dao.bean.AttendanceInfoBean;
import com.dongfangyuxin.common.dao.bean.AttendanceInfoBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AttendanceInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=AttendanceInfoBeanSqlProvider.class, method="countByExample")
    long countByExample(AttendanceInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @DeleteProvider(type=AttendanceInfoBeanSqlProvider.class, method="deleteByExample")
    int deleteByExample(AttendanceInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Delete({
        "delete from sagittarius..attendance_info",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Insert({
        "insert into sagittarius..attendance_info (STAFF_CODE, START_TIME, ",
        "END_TIME, S_CREATOR, ",
        "S_CREATE_DATE, S_OPERATOR, ",
        "S_OPERATOR_DATE)",
        "values (#{staffCode,jdbcType=CHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{sCreator,jdbcType=CHAR}, ",
        "#{sCreateDate,jdbcType=TIMESTAMP}, #{sOperator,jdbcType=CHAR}, ",
        "#{sOperatorDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AttendanceInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @InsertProvider(type=AttendanceInfoBeanSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(AttendanceInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=AttendanceInfoBeanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="STAFF_CODE", property="staffCode", jdbcType=JdbcType.CHAR),
        @Result(column="START_TIME", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<AttendanceInfoBean> selectByExample(AttendanceInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Select({
        "select",
        "ID, STAFF_CODE, START_TIME, END_TIME, S_CREATOR, S_CREATE_DATE, S_OPERATOR, ",
        "S_OPERATOR_DATE",
        "from sagittarius..attendance_info",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="STAFF_CODE", property="staffCode", jdbcType=JdbcType.CHAR),
        @Result(column="START_TIME", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    AttendanceInfoBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=AttendanceInfoBeanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AttendanceInfoBean record, @Param("example") AttendanceInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=AttendanceInfoBeanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AttendanceInfoBean record, @Param("example") AttendanceInfoBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=AttendanceInfoBeanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AttendanceInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..attendance_info
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Update({
        "update sagittarius..attendance_info",
        "set STAFF_CODE = #{staffCode,jdbcType=CHAR},",
          "START_TIME = #{startTime,jdbcType=TIMESTAMP},",
          "END_TIME = #{endTime,jdbcType=TIMESTAMP},",
          "S_CREATOR = #{sCreator,jdbcType=CHAR},",
          "S_CREATE_DATE = #{sCreateDate,jdbcType=TIMESTAMP},",
          "S_OPERATOR = #{sOperator,jdbcType=CHAR},",
          "S_OPERATOR_DATE = #{sOperatorDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AttendanceInfoBean record);
}