package com.dongfangyuxin.common.dao;

import com.dongfangyuxin.common.dao.bean.Classification;
import com.dongfangyuxin.common.dao.bean.ClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=ClassificationSqlProvider.class, method="countByExample")
    long countByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @DeleteProvider(type=ClassificationSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Delete({
        "delete from sagittarius..classification",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Insert({
        "insert into sagittarius..classification (CODE, NAME, ",
        "PARENT, S_CREATOR, S_CREATE_DATE, ",
        "S_OPERATOR, S_OPERATOR_DATE)",
        "values (#{code,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{parent,jdbcType=CHAR}, #{sCreator,jdbcType=CHAR}, #{sCreateDate,jdbcType=TIMESTAMP}, ",
        "#{sOperator,jdbcType=CHAR}, #{sOperatorDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @InsertProvider(type=ClassificationSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=ClassificationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARENT", property="parent", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Classification> selectByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Select({
        "select",
        "ID, CODE, NAME, PARENT, S_CREATOR, S_CREATE_DATE, S_OPERATOR, S_OPERATOR_DATE",
        "from sagittarius..classification",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARENT", property="parent", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    Classification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=ClassificationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=ClassificationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=ClassificationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..classification
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Update({
        "update sagittarius..classification",
        "set CODE = #{code,jdbcType=CHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "PARENT = #{parent,jdbcType=CHAR},",
          "S_CREATOR = #{sCreator,jdbcType=CHAR},",
          "S_CREATE_DATE = #{sCreateDate,jdbcType=TIMESTAMP},",
          "S_OPERATOR = #{sOperator,jdbcType=CHAR},",
          "S_OPERATOR_DATE = #{sOperatorDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Classification record);
}