package com.dongfangyuxin.common.dao;

import com.dongfangyuxin.common.dao.bean.ExpenseInfoDetailBean;
import com.dongfangyuxin.common.dao.bean.ExpenseInfoDetailBeanExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface ExpenseInfoDetailBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @SelectProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="countByExample")
    long countByExample(ExpenseInfoDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @DeleteProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExpenseInfoDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @Delete({
        "delete from expense_info_detail",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @Insert({
        "insert into expense_info_detail (CODE, TYPE, AMOUNT, ",
        "S_CREATOR, S_CREATE_DATE, ",
        "S_OPERATOR, S_OPERATOR_DATE)",
        "values (#{code,jdbcType=CHAR}, #{type,jdbcType=CHAR}, #{amount,jdbcType=DECIMAL}, ",
        "#{sCreator,jdbcType=CHAR}, #{sCreateDate,jdbcType=TIMESTAMP}, ",
        "#{sOperator,jdbcType=CHAR}, #{sOperatorDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ExpenseInfoDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @InsertProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ExpenseInfoDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @SelectProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.CHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ExpenseInfoDetailBean> selectByExample(ExpenseInfoDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @Select({
        "select",
        "ID, CODE, TYPE, AMOUNT, S_CREATOR, S_CREATE_DATE, S_OPERATOR, S_OPERATOR_DATE",
        "from expense_info_detail",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.CHAR),
        @Result(column="AMOUNT", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    ExpenseInfoDetailBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @UpdateProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ExpenseInfoDetailBean record, @Param("example") ExpenseInfoDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @UpdateProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ExpenseInfoDetailBean record, @Param("example") ExpenseInfoDetailBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @UpdateProvider(type=ExpenseInfoDetailBeanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ExpenseInfoDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense_info_detail
     *
     * @mbg.generated Sat Jul 22 22:38:45 CST 2017
     */
    @Update({
        "update expense_info_detail",
        "set CODE = #{code,jdbcType=CHAR},",
          "TYPE = #{type,jdbcType=CHAR},",
          "AMOUNT = #{amount,jdbcType=DECIMAL},",
          "S_CREATOR = #{sCreator,jdbcType=CHAR},",
          "S_CREATE_DATE = #{sCreateDate,jdbcType=TIMESTAMP},",
          "S_OPERATOR = #{sOperator,jdbcType=CHAR},",
          "S_OPERATOR_DATE = #{sOperatorDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExpenseInfoDetailBean record);
}