package com.dongfangyuxin.common.dao;

import com.dongfangyuxin.common.dao.bean.MaterialRequisitionBean;
import com.dongfangyuxin.common.dao.bean.MaterialRequisitionBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaterialRequisitionBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=MaterialRequisitionBeanSqlProvider.class, method="countByExample")
    long countByExample(MaterialRequisitionBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @DeleteProvider(type=MaterialRequisitionBeanSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaterialRequisitionBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Delete({
        "delete from sagittarius..material_requisition",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Insert({
        "insert into sagittarius..material_requisition (CODE, TASK_CODE, ",
        "COUNT, OPERATOR, OPERATING_TIME, ",
        "S_CREATOR, S_CREATE_DATE, ",
        "S_OPERATOR, S_OPERATOR_DATE)",
        "values (#{code,jdbcType=CHAR}, #{taskCode,jdbcType=CHAR}, ",
        "#{count,jdbcType=INTEGER}, #{operator,jdbcType=CHAR}, #{operatingTime,jdbcType=TIMESTAMP}, ",
        "#{sCreator,jdbcType=CHAR}, #{sCreateDate,jdbcType=TIMESTAMP}, ",
        "#{sOperator,jdbcType=CHAR}, #{sOperatorDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(MaterialRequisitionBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @InsertProvider(type=MaterialRequisitionBeanSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(MaterialRequisitionBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @SelectProvider(type=MaterialRequisitionBeanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="TASK_CODE", property="taskCode", jdbcType=JdbcType.CHAR),
        @Result(column="COUNT", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="OPERATOR", property="operator", jdbcType=JdbcType.CHAR),
        @Result(column="OPERATING_TIME", property="operatingTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<MaterialRequisitionBean> selectByExample(MaterialRequisitionBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Select({
        "select",
        "ID, CODE, TASK_CODE, COUNT, OPERATOR, OPERATING_TIME, S_CREATOR, S_CREATE_DATE, ",
        "S_OPERATOR, S_OPERATOR_DATE",
        "from sagittarius..material_requisition",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.CHAR),
        @Result(column="TASK_CODE", property="taskCode", jdbcType=JdbcType.CHAR),
        @Result(column="COUNT", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="OPERATOR", property="operator", jdbcType=JdbcType.CHAR),
        @Result(column="OPERATING_TIME", property="operatingTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_CREATOR", property="sCreator", jdbcType=JdbcType.CHAR),
        @Result(column="S_CREATE_DATE", property="sCreateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="S_OPERATOR", property="sOperator", jdbcType=JdbcType.CHAR),
        @Result(column="S_OPERATOR_DATE", property="sOperatorDate", jdbcType=JdbcType.TIMESTAMP)
    })
    MaterialRequisitionBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=MaterialRequisitionBeanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MaterialRequisitionBean record, @Param("example") MaterialRequisitionBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=MaterialRequisitionBeanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MaterialRequisitionBean record, @Param("example") MaterialRequisitionBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @UpdateProvider(type=MaterialRequisitionBeanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MaterialRequisitionBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sagittarius..material_requisition
     *
     * @mbg.generated Tue Jul 11 00:06:29 CST 2017
     */
    @Update({
        "update sagittarius..material_requisition",
        "set CODE = #{code,jdbcType=CHAR},",
          "TASK_CODE = #{taskCode,jdbcType=CHAR},",
          "COUNT = #{count,jdbcType=INTEGER},",
          "OPERATOR = #{operator,jdbcType=CHAR},",
          "OPERATING_TIME = #{operatingTime,jdbcType=TIMESTAMP},",
          "S_CREATOR = #{sCreator,jdbcType=CHAR},",
          "S_CREATE_DATE = #{sCreateDate,jdbcType=TIMESTAMP},",
          "S_OPERATOR = #{sOperator,jdbcType=CHAR},",
          "S_OPERATOR_DATE = #{sOperatorDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MaterialRequisitionBean record);
}